[package]
name = "cardano"
version = "0.5.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "../../README.md"
description = "no_std-first Cardano protocol building blocks for Rust."

[features]
default = []
std = [
    "cardano-valkyoth-cbor/std",
    "cardano-valkyoth-primitives/std",
]
node = []
rpc = []
sanitization = []
signer = []
testkit = []

[dependencies]
cardano-valkyoth-cbor.workspace = true
cardano-valkyoth-primitives.workspace = true

[lints]
workspace = true
